#!/bin/bash
#Current escapees are for BRE only
sed -e's#\\#\\\\#g'	\
-e 's#/#\\/#g'		\
-e 's#&#\\&#g'		\
-e 's#=#\\=#g'		\
-e 's#\.#\\.#g'		\
-e 's#\^#\\^#g'		\
-e 's#\$#\\$#g'		\
-e 's#\*#\\*#g'		\
-e 's#\[#\\[#g'		\
-e 's#\]#\\]#g'		\
-e 's#\\|#\\\|#g'	\
-e "s#\"#\\\\\"#g"		\
-e "s#\'#\\\'#g"		\
-e "s#\`#\\\`#g"		\
file1
