#!/bin/bash
opts=( "$@" )
#if no argument is passed this for loop will be skipped
for ((i=0;i<$#;i++)) do
case "${opts[$i]}" in
   -abc)
   
	# "${opts[$((i+1))]}" is the immediately follwing option
	[[ "${opts[$((i+1))]}" != "" ]] &&
	value="${opts[$((i+1))]}"
	echo "$value"
	((i++))
	#skips the nex adjacent argument as it is already taken
	
	;;
	
   -h)
   #dummy help option
   echo "Options are [-abc value], -h"
   
	;;
	
   *)
   #other unknown options
   echo invalid option
 	break
	
	;;
esac
done
